### ISSUE TITLE
Missing blankline from title to description when coming from `$schema`

### ISSUE THREAD

**Issue by Atinux** [unjs/untyped#70]
### Environment

Latest version

### Reproduction

https://untyped.unjs.io/#eyJlZGl0b3JUYWIiOiJyZWZlcmVuY2UiLCJvdXRwdXRUYWIiOiJ0eXBlcyIsInJlZiI6Ii8qKiBAdW50eXBlZCAqL1xuZXhwb3J0IGZ1bmN0aW9uIHNlbmRNZXNzYWdlIChtZXNzYWdlOiBzdHJpbmcsIGRhdGUgPSBuZXcgRGF0ZSgpLCBmbGFzaD86IGJvb2xlYW4pOiBzdHJpbmcge1xuICByZXR1cm4gJ09LJ1xufVxuXG5leHBvcnQgY29uc3QgY29uZmlnID0ge1xuICAgIG51eHRJY29uOiB7XG4gICAgICAgICRzY2hlbWE6IHtcbiAgICAgICAgICAgIHRpdGxlOiAnTnV4dCBJY29uJyxcbiAgICAgICAgICAgIGRlc2NyaXB0aW9uOiAnQ29uZmlndXJlIHRoZSBkZWZhdWx0cyBvZiBOdXh0IEljb24nXG4gICAgICAgIH1cbiAgICB9XG59IiwiaW5wdXQiOiJleHBvcnQgY29uc3QgY29uZmlnID0ge1xuICAgIG5hbWU6ICdmb28nLFxuICAgIGRpbWVuc2lvbnM6IHtcbiAgICAgICAgaGVpZ2h0OiAyNVxuICAgIH0sXG4gICAgdGFnczogWydjdXN0b20nXVxufSJ9

### Describe the bug

![CleanShot 2023-01-13 at 17 46 09@2x](https://user-images.githubusercontent.com/904724/212373980-a2fba546-57ff-48a8-86b2-8e18f55e4036.png)

Because we miss the blankline, it renders like this:

<img width="965" alt="CleanShot 2023-01-13 at 17 48 37@2x" src="https://user-images.githubusercontent.com/904724/212374365-b4718b54-e2ed-4467-b37d-2df02f605bc3.png">

Instead of:
<img width="956" alt="CleanShot 2023-01-13 at 17 49 17@2x" src="https://user-images.githubusercontent.com/904724/212374422-7e1e9158-01fd-4718-970c-c07b3e638d64.png">

**Comment by pi0** [comment]
Issue is that, we intentionally strip empty (+1) lines  from description but probably we can add them between all final description before generation 👍🏼

**Comment by Atinux** [comment]
It would be great indeed, that will improve the DX of Nuxt Icon auto complete

**Comment by pi0** [comment]
Pushed a fix. Can you plese double check on playground before release?

**Comment by Atinux** [comment]
Looks good on the playground:
![CleanShot 2023-01-13 at 18.05.06@2x.png](https://volta.s3.fr-par.scw.cloud/Clean_Shot_2023_01_13_at_18_05_06_2x_c94ce31b29.png)

**Comment by Atinux** [comment]
Happy to push a release for me to try on Nuxt Icon @pi0 ?
